# Generated by Django 5.1.1 on 2024-09-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_boook_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='BookTitle',
            new_name='book_title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='ReleaseYear',
            new_name='release_year',
        ),
    ]
